apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomo-align
  namespace: em
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomo-align
  template:
    metadata:
      labels:
        app: tomo-align
    spec:
      securityContext:
        runAsUser: 37679
        runAsGroup: 37829
      containers:
      - name: tomo-align-runner
        image: gcr.io/diamond-pubreg/em/tomo_align:relion
        imagePullPolicy: Always
        resources:
          requests:
            nvidia.com/gpu: "1"
          limits:
            memory: 25Gi
            nvidia.com/gpu: "1"
        command: ["/bin/sh"]
        args: 
          - -c
          - >-
              source "/conda/etc/profile.d/conda.sh" && conda activate /install/pythonenv && zocalo.service -s TomoAlign -e devrmq
        env:
        - name: KUBERNETES
          value: "1"
        - name: ZOCALO_CONFIG
          value: "/zocalo/config/zocalo-dev-config.yaml"
        - name: ISPYB_CREDENTIALS
          value: "/zocalo/secrets/ispyb-dev.cfg"
        - name: LD_LIBRARY_PATH
          value: "/IMOD/4.11.1/IMOD/lib:/IMOD/4.11.1/IMOD/qtlib"
        - name: IMOD_DIR
          value: "/IMOD/4.11.1/IMOD"
        volumeMounts:
        - name: config-file
          mountPath: /zocalo/config
        - name: secrets
          mountPath: /zocalo/secrets
        - name: dls
          mountPath: /dls
          mountPropagation: HostToContainer
          readOnly: true
      volumes:
      - name: config-file
        configMap:
          name: zocalo-configmap-dev
      - name: secrets
        projected:
          defaultMode: 0444
          sources:
          - secret: 
              name: dev-ispyb-secret
          - secret:
              name: staging-rmq-creds
          - secret:
              name: staging-rmq-api-reader
      - name: dls
        hostPath:
          path: /dls
          type: Directory
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: nodetype
        operator: Equal
        value: gpu
