stages:
- stage: tests
  displayName: Tests
  jobs:
  - job: checks
    displayName: static code analysis
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: UsePythonVersion@0
        displayName: Set up python
        inputs:
          versionSpec: 3.8

      - bash: |
          python .azure-pipelines/syntax-validation.py
        displayName: Syntax validation

      - bash: |
          pip install flake8
          python .azure-pipelines/flake8-validation.py
        displayName: Flake8 validation

  - template: .azure-pipelines/tox.yml
    parameters:
      name: linux
      python: 3.6
      vmImage: ubuntu-latest

  - template: .azure-pipelines/tox.yml
    parameters:
      name: macOS
      python: 3.6
      vmImage: macOS-latest

  - template: .azure-pipelines/tox.yml
    parameters:
      name: windows
      python: 3.6
      vmImage: windows-latest

- stage: platform_tests
  displayName: Full platform checks
  dependsOn: tests
  condition: False
  jobs:
  - job: linux
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        python36:
          PYTHON_VERSION: 3.6
        python37:
          PYTHON_VERSION: 3.7
        python38:
          PYTHON_VERSION: 3.8
      maxParallel: 2

    steps:
    - template: .azure-pipelines/ci-unix.yml

  - job: macOS
    pool:
      vmImage: macOS-latest
    strategy:
      matrix:
        python36:
          PYTHON_VERSION: 3.6
        python37:
          PYTHON_VERSION: 3.7
        python38:
          PYTHON_VERSION: 3.8
      maxParallel: 2

    steps:
    - template: .azure-pipelines/ci-unix.yml

  - job: windows
    pool:
      vmImage: windows-latest
    strategy:
      matrix:
        python36:
          PYTHON_VERSION: 3.6
        python37:
          PYTHON_VERSION: 3.7
        python38:
          PYTHON_VERSION: 3.8
      maxParallel: 2

    steps:
    - template: .azure-pipelines/ci-windows.yml
