codecov:
  token: 717b4876-f90a-448f-9036-38fc0f0a4fd2

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 100%
    patch:
      default:
        target: 0%
        threshold: 100%

comment:
  layout: "diff, flags"
  branches:
    - master
  after_n_builds: 3
