#!/bin/bash
# A simple script to mimic the behaviour of the Relion pipeline.

echo "Relion starting up"

if [ ! -e Movies ]; then
  echo "No movies directory found"
  exit 1
fi
sleep 5

echo "Starting Motion Correction"
cp -r /dls/science/groups/scisoft/DIALS/dials_data/relion_tutorial_data/MotionCorr ./
sleep 10

echo "Starting CTFFind"
cp -r /dls/science/groups/scisoft/DIALS/dials_data/relion_tutorial_data/CtfFind ./
sleep 10

echo "Finished"
