apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-submission
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cluster-submission
  template:
    metadata:
      labels:
        app: cluster-submission
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      containers:
      - name: cluster-submission-runner
        image: {{ .Values.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: {{ .Values.cpuLimit }}
            memory: {{ .Values.memoryLimit }}
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              {{ .Values.command }}
        env:
        - name: KUBERNETES
          value: "1"
        - name: ZOCALO_CONFIG
          value: "/zocalo/config/zocalo-dev-config.yaml"
        - name: ISPYB_CREDENTIALS
          value: "/zocalo/secrets/{{ .Values.dbFileName }}"
        volumeMounts:
        - name: config-file
          mountPath: /zocalo/config
        - name: secrets
          mountPath: /zocalo/secrets
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{ end }}
      volumes:
      - name: config-file
        configMap:
          name: {{ .Values.configMap }}
      - name: secrets
        projected:
          defaultMode: 0444
          sources:
          - secret:
              name: {{ .Values.dbSecretName }}
          - secret:
              name: {{ .Values.rmqSecretName }}
          - secret:
              name: {{ .Values.rmqApiSecretName }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{ end }}
{{- if .Values.scaleOnQueueLength }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cluster-submission
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    name: cluster-submission
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ .Values.global.rmqHost }}
        queueName: cluster_submission
        mode: QueueLength
        value: "{{ .Values.queueLengthTrigger }}"
  minReplicaCount: {{ .Values.minReplicaCount }}
  maxReplicaCount: {{ .Values.maxReplicaCount }}
  idleReplicaCount: {{ .Values.idleReplicaCount }}
{{ end }}
