apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomo-align-iris
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: tomo-align-iris
  template:
    metadata:
      labels:
        app: tomo-align-iris
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      containers:
      - name: tomo-align-iris-runner
        image: {{ .Values.image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "250m"
        command: ["/bin/sh"]
        args: 
          - -c
          - >-
              {{ .Values.command }}
        env:
        - name: KUBERNETES
          value: "1"
        - name: ZOCALO_CONFIG
          value: "/zocalo/config/zocalo-dev-config.yaml"
        - name: ISPYB_CREDENTIALS
          value: "/zocalo/secrets/{{ .Values.dbFileName }}"
        - name: LD_LIBRARY_PATH
          value: "/IMOD/4.11.1/IMOD/lib:/IMOD/4.11.1/IMOD/qtlib"
        - name: IMOD_DIR
          value: "/IMOD/4.11.1/IMOD"
        - name: CONDOR_CONFIG
          value: "ONLY_ENV"
        volumeMounts:
        - name: config-file
          mountPath: /zocalo/config
        - name: secrets
          mountPath: /zocalo/secrets
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{ end }}
      volumes:
      - name: config-file
        configMap:
          name: zocalo-conf
      - name: secrets
        projected:
          defaultMode: 0444
          sources:
          - secret: 
              name: {{ .Values.dbSecretName }}
          - secret:
              name: {{ .Values.rmqSecretName }}
          - secret:
              name: {{ .Values.rmqApiSecretName }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{ end }}
{{- if .Values.scaleOnQueueLength }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: tomo-align-iris
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    name: tomo-align-iris
  triggers:
    - type: rabbitmq
      metadata:
        host: {{ .Values.global.rmqHost }}
        queueName: tomo_align
        mode: QueueLength
        value: "{{ .Values.queueLengthTrigger }}"
{{ end }}
