global:

  namespace: my-namespace
  runAsUser: user-id
  runAsGroup: group-id

cryolo:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg

ctffind:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg

dispatcher:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg

images:
  replicas: 2
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg

ispyb:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg

motioncorr:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg

tomo_align:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: dls
    hostPath:
      path: /dls
      type: Directory
  extraVolumeMounts:
  - mountPath: /dls
    name: dls
    mountPropagation: HostToContainer
    readOnly: true
  dbSecretName: dev-db # name for database credentials
  dbFileName: db-dev.cfg
