global:

  namespace: my-namespace
  runAsUser: user-id
  runAsGroup: group-id

ctffind:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true

dispatcher:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true

images:
  replicas: 2
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true

ispyb:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true

motioncorr:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: home
    hostPath:
      path: /home
      type: Directory
  extraVolumeMounts:
  - mountPath: /home
    name: home
    mountPropagation: HostToContainer
    readOnly: true

tomo_align:
  replicas: 1
  image: gcr.io/image/path
  command: zocalo.service -s service-name -e environment
  extraVolumes:
  - name: dls
    hostPath:
      path: /dls
      type: Directory
  extraVolumeMounts:
  - mountPath: /dls
    name: dls
    mountPropagation: HostToContainer
    readOnly: true
