apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomo-align
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: tomo-align
  template:
    metadata:
      labels:
        app: tomo-align
    spec:
      securityContext:
        runAsUser: {{ .Values.global.runAsUser }}
        runAsGroup: {{ .Values.global.runAsGroup }}
      containers:
      - name: tomo-align-runner
        image: {{ .Values.image }}
        imagePullPolicy: Always
        resources:
          requests:
            nvidia.com/gpu: "1"
          limits:
            memory: 25Gi
            nvidia.com/gpu: "1"
        command: ["/bin/sh"]
        args: 
          - -c
          - >-
              {{ .Values.command }}
        env:
        - name: KUBERNETES
          value: "1"
        - name: ZOCALO_CONFIG
          value: "/zocalo/config/zocalo-dev-config.yaml"
        - name: ISPYB_CREDENTIALS
          value: "/zocalo/secrets/{{ .Values.dbFileName }}"
        - name: LD_LIBRARY_PATH
          value: "/IMOD/4.11.1/IMOD/lib:/IMOD/4.11.1/IMOD/qtlib"
        - name: IMOD_DIR
          value: "/IMOD/4.11.1/IMOD"
        volumeMounts:
        - name: config-file
          mountPath: /zocalo/config
        - name: secrets
          mountPath: /zocalo/secrets
{{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
{{ end }}
      volumes:
      - name: config-file
        configMap:
          name: zocalo-configmap-dev
      - name: secrets
        projected:
          defaultMode: 0444
          sources:
          - secret: 
              name: {{ .Values.dbSecretName }}
          - secret:
              name: staging-rmq-creds
          - secret:
              name: staging-rmq-api-reader
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
{{ end }}
      tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: nodetype
        operator: Equal
        value: gpu
