steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
  displayName: 'Use Python $(PYTHON_VERSION)'

- script: |
    python -m pip install -r requirements_dev.txt pytest-azurepipelines
  displayName: Install dependencies

- script: |
    pip install --no-deps --disable-pip-version-check -e .
  displayName: Install relion package

- script: |
    pytest -v -ra --regression \
        --cov=relion --cov-report=xml --cov-branch --no-coverage-upload \
        || echo "##vso[task.complete result=Failed;]Some tests failed"
  displayName: Run tests

- script: |
    bash <(curl -s https://codecov.io/bash) -n "Python $(PYTHON_VERSION) $(Agent.OS)"
  displayName: 'Publish coverage stats'
  continueOnError: True
  timeoutInMinutes: 2
