steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
  displayName: 'Use Python $(PYTHON_VERSION)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements_dev.txt
  displayName: Install dependencies

- script: |
    pytest -v -ra \
        --cov=relion --cov-report=html --cov-report=xml --cov-branch \
        --regression || echo "##vso[task.complete result=Failed;]Some tests failed"
  displayName: Run tests

#- script: |
#    bash <(curl -s https://codecov.io/bash) -n "Python $(PYTHON_VERSION) $(Agent.OS)"
#  displayName: 'Publish coverage stats'
#  continueOnError: True
#  timeoutInMinutes: 3
