jobs:
 - job: tox_${{ parameters.name }}
   displayName: ${{ parameters.name }} python${{ parameters.python }}
   pool:
     vmImage: ${{ parameters.vmImage }}
   steps:
   - task: UsePythonVersion@0
     inputs:
       versionSpec: ${{ parameters.python }}
     displayName: Use Python ${{ parameters.python }}

   - script: |
       python -m pip install --upgrade pip
       pip install tox
     displayName: Set up tox

   - script: |
       tox -e azure
     displayName: Run tests

   - task: PublishTestResults@2
     condition: succeededOrFailed()
     inputs:
       testResultsFiles: '**/test-*.xml'
       testRunTitle: "Publish tox test results for ${{ parameters.name }} and Python ${{ parameters.python }}"
